### ISSUE TITLE
How to change font-family and font-size?

### ISSUE THREAD

**Issue by TWpower** [aron-bordin/neo-hpstr-jekyll-theme#53]
I modified both codes but nothing works... how to change code font-size and font-family?

___coderay.scss__
```scss
$base-font: 'Lato', Calibri, Arial, sans-serif;
$heading-font: $base-font;
$caption-font: $base-font;
$code-font: Arial;
$alt-font: serif;
```

___variables.scss__

```scss
.CodeRay {
  font-family: $code-font;
  @include font(12);
  color: #d0d0d0;
  margin-bottom: 1.5em;
  @include rounded(3px);
}
```
